### ISSUE TITLE
storybook-wc fails if several web components

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#32]
Seems to be a concurrency loads of angular sources that create issues while running storybook-wc with severals web components.

https://geonetwork.github.io/geonetwork-ui/master/storybook-wc/

```
VM1722 main.647ae3ccdecb25ee2746.bundle.js:12042 ERROR DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at CustomElementRegistry.target.(anonymous function) [as define] (http://localhost:4202/vendors~main.647ae3ccdecb25ee2746.bundle.js:166506:35)
    at GnResultsListModule.ngDoBootstrap (http://localhost:4202/main.647ae3ccdecb25ee2746.bundle.js:1743:2000)
    at PlatformRef._moduleDoBootstrap (http://localhost:4202/main.647ae3ccdecb25ee2746.bundle.js:21107:689)
```

Securing the registry does not work
```typescript
    if(!customElements.get(WC_TAG_NAME)) {
      customElements.define(WC_TAG_NAME, customButton)
    }
```

If we only load one `.stories` file of web component, the storybook works.

**Comment by jahow** [comment]
This is not the case anymore on master, see https://geonetwork.github.io/geonetwork-ui/master/storybook-wc/

Closing
